author:
  name: Alfie Ng
  email: nycnami@yahoo.com.hk
title: 食飯
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c9a2fe8a-40a0-456d-b42e-16188ef39509.jpg
description: 位於台北市松山區的港式餐廳，由兩位愛吃愛玩的香港年輕人主理
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.207841
  brandColors:
    - '#060407'
    - '#FFF9E9'
    - '#665136'
    - '#B08B57'
    - '#22A88B'
  rhythmicContrast: 0.3893662
typography_spectrum: 0.8265306
layout_spectrum: 0
name: 食飯
