typography_spectrum: 0.8265306
color:
  saturation: 0.02112063
  lightness: 0.4142689
  brandStrength: 1
  brandColors:
    - '#060407'
    - '#FFF9E9'
    - '#665136'
    - '#B08B57'
    - '#22A88B'
  rhythmicContrast: 0.6272077
layout_spectrum: 0
name: 食飯 SikFan
title: 食飯
description: 位於台北市松山區的港式餐廳，由兩位愛吃愛玩的香港年輕人主理
